-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, TupleSections, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase #-}

module Project.Scenes.GUI where
import Prelude
import Project.Support
import Godot
import GHC.TypeLits

import Godot.Core.CanvasLayer()
import Godot.Core.HBoxContainer()
import Godot.Core.Label()

instance SceneResourcePath "GUI" where
  sceneResourcePath = "res://GUI.tscn"


instance SceneRoot "GUI" where
  type SceneRootNode "GUI" = "GUI"


instance SceneNode        "GUI" "GUI" where
  type SceneNodeType      "GUI" "GUI" = CanvasLayer
  type SceneNodeName      "GUI" "GUI" = "GUI"
  type SceneNodeIsHaskell "GUI" "GUI" = 'Nothing


instance SceneNode        "GUI" "HBoxContainer" where
  type SceneNodeType      "GUI" "HBoxContainer" = HBoxContainer
  type SceneNodeName      "GUI" "HBoxContainer" = "HBoxContainer"
  type SceneNodeIsHaskell "GUI" "HBoxContainer" = 'Nothing


instance SceneNode        "GUI" "HBoxContainer/Speed" where
  type SceneNodeType      "GUI" "HBoxContainer/Speed" = Label
  type SceneNodeName      "GUI" "HBoxContainer/Speed" = "Speed"
  type SceneNodeIsHaskell "GUI" "HBoxContainer/Speed" = 'Nothing


instance SceneNode        "GUI" "HBoxContainer/Units" where
  type SceneNodeType      "GUI" "HBoxContainer/Units" = Label
  type SceneNodeName      "GUI" "HBoxContainer/Units" = "Units"
  type SceneNodeIsHaskell "GUI" "HBoxContainer/Units" = 'Nothing

