-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, TupleSections, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase #-}

module Project.Scenes.Player where
import Prelude
import Project.Support
import Godot
import GHC.TypeLits

import Godot.Core.Spatial()
import Godot.Core.Camera()
import Godot.Core.CollisionShape()
import Godot.Core.KinematicBody()
import Godot.Core.RayCast()

instance SceneResourcePath "Player" where
  sceneResourcePath = "res://Player.tscn"


instance SceneRoot "Player" where
  type SceneRootNode "Player" = "Player"


instance SceneNode        "Player" "CamBase" where
  type SceneNodeType      "Player" "CamBase" = Spatial
  type SceneNodeName      "Player" "CamBase" = "CamBase"
  type SceneNodeIsHaskell "Player" "CamBase" = 'Nothing


instance SceneNode        "Player" "CamBase/Camera" where
  type SceneNodeType      "Player" "CamBase/Camera" = Camera
  type SceneNodeName      "Player" "CamBase/Camera" = "Camera"
  type SceneNodeIsHaskell "Player" "CamBase/Camera" = 'Nothing


instance SceneNode        "Player" "CollisionShape" where
  type SceneNodeType      "Player" "CollisionShape" = CollisionShape
  type SceneNodeName      "Player" "CollisionShape" = "CollisionShape"
  type SceneNodeIsHaskell "Player" "CollisionShape" = 'Nothing


instance SceneNode        "Player" "Player" where
  type SceneNodeType      "Player" "Player" = KinematicBody
  type SceneNodeName      "Player" "Player" = "Player"
  type SceneNodeIsHaskell "Player" "Player" = 'Nothing


instance SceneNode        "Player" "RayCast" where
  type SceneNodeType      "Player" "RayCast" = RayCast
  type SceneNodeName      "Player" "RayCast" = "RayCast"
  type SceneNodeIsHaskell "Player" "RayCast" = 'Nothing

