-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE DataKinds #-}

module Project.Requirements where
import Project.Support

type Nodes = '[OneResourceNode "GUI" "GUI", OneResourceNode "Player" "Player"]
