-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

module Project.Scenes (module M) where
import qualified Project.Scenes.GUI as M
import qualified Project.Scenes.Player as M
import qualified Project.Scenes.World as M

